typography_spectrum: 0.3383744868915528
color:
  brandStrength: 0.7534460695460439
  lightness: 0.49417145014740527
  saturation: 0.11298604938201606
  rhythmicContrast: 0.09458680357784033
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.20672783139161766
name: Niki Papachristou
title: Niki Papachristou
